### ISSUE TITLE
As a repo owner I need to be able to create a changelog

### ISSUE THREAD

**Issue by aaronmallen** [JustShipIt/TheDepot#15]
## Goal
Allow for repo owners who use our service to create a changelog for their repo.

## Dev Notes
* "Activating" should be handled in the same way Travis-ci.org handles activating builds for a repo.  We should list all of the repo owners repos and provide a radio to activate changelog for that repo.

* Getting the changelog data can be handled several ways.  We will discuss how we intend to get changelog data here in this story.

  1. We can scrape the repo for a CHANGELOG.md and use the data stored there to generate a changelog
  1. We can define a format to our users and scrape the repo's commits to generate a changelog from the commit data.
  1. We can define a format to our users and scrape the repo's PR's to generate a changelog from the comment data.
  1. We can do all of the above.

## Scope Change:
#27 will handle parsing the data from PR comments.  Change the changelog model to accept the format of this parsed service.

Model will need the following fields:
* `change_type` (this can be changed, added, fixed)
* `version`
* `release_status` (whether or not the new changes are in master or not)
* `change` (what was changed)

**Comment by aaronmallen** [comment]
@samsheff for v1.0.0 I'm thinking we take the path of least resistance.  We simply scrape the repo for CHANGELOG.md and use the data there.  We would want to implement option 2 asap though and have some form of setting to use commit logs, or a CHANGELOG.md, or both.

**Comment by samsheff** [comment]
@aaronmallen Why not just use PR titles?

**Comment by aaronmallen** [comment]
@samsheff see my comment in #21

**Comment by aaronmallen** [comment]
@samsheff however if pulling data in from PR's is going to be easier than looking for a changelog.md in the repo lets go that route for v1.0.0. But not titles, pull PR content.  We want to implement all three eventually and allow the user to choose which method fits their workflow.

**Comment by samsheff** [comment]
@aaronmallen :+1:

**Comment by aaronmallen** [comment]
Ok so PR's for v1.0.0?

**Comment by aaronmallen** [comment]
This impedes the project. Solution: resolve the issue.

**Comment by aaronmallen** [comment]
broke half of this story into #27. See scope change in issue description.
