### ISSUE TITLE
As a repo owner I need a readme badge

### ISSUE THREAD

**Issue by aaronmallen** [JustShipIt/TheDepot#18]
## Goal
Provide a badge for repo README.md files

**Comment by aaronmallen** [comment]
shields.io might be a good solution for this.

**Comment by samsheff** [comment]
@aaronmallen Never heard of that, but it looks neat. I'm not against

**Comment by aaronmallen** [comment]
@samsheff why doesn't this work? https://gist.github.com/aaronmallen/6ea6e2fd17eab15ed2bc
