### ISSUE TITLE
As a developer I need to standardize required formats

### ISSUE THREAD

**Issue by aaronmallen** [JustShipIt/TheDepot#21]
## Goal
Create and document and standardize format we will expect our users to use to appropriately create changelog data.

**Comment by aaronmallen** [comment]
@samsheff I'm thinking the changelog data would work like so:

we would use tags to decide what version we are in of the repo.  If we're scraping the repo for CHANGELOG.md we could do it two ways.  

(preffered) -> Expect to find a header element `# vX.X.X` in the changelog matching the tags.  Under each header element expect to find 3 sections formatted with 
```
SECTION
------------
```
the three section we should expect to find are changed, added, fixed.  We would then expect to find a bulleted list of items under each section.

**example doc**
```
#CHANGELOG.md

# v1.1.0
Changed
------------
* someMethod now returns a boolean
Added
------------
* users can now specify roles
Fixed
------------
* a bug that crashed the server

# v1.0.1
Changed
------------
* some change
```

This is the preferred method because it leaves the CHANGELOG.md file human readable within the repo.

(other way) -> same format as outlined above without specifying version numbers in the CHANGELOG.md file.  Basically the file would just have the three sections and we would check the diff between versions for what was added to the changelog and use that data.

If we are going to use pull requests, and commit messages we would anticipate the same format:

```
#commit f64ce3
Changed
--------------
* I changed this
```

we would then scrape the commits or PRs for messages in this format and ever commit that falls in between the latest tag and the current tag would be pulled in as changelog data.  

I hope all of that makes sense let me know what you think or if you have questions.

**Comment by samsheff** [comment]
@aaronmallen Love that. Also, I think the best way to get the changelog info is to scrape PR titles. What do you think about that?

**Comment by aaronmallen** [comment]
@samsheff what would we expect to grab from PR titles? I don't necessarily like placing any requirements on PR titles, I think it would be best to pull in PR comment content instead.  Most people like to title their issues and PR's pretty concisely.

**Comment by samsheff** [comment]
@aaronmallen This is true. Let's just scrape it for now, but the one requirement is finding a central datapoint we can use - I just don't know what that is yet.

**Comment by aaronmallen** [comment]
@samsheff lets keep the discussion in this story to formatting.  How do you feel about the format suggested here?

**Comment by samsheff** [comment]
@aaronmallen Why not just use github markdown (assuming that's not what you're trying to do in the first place)?

**Comment by samsheff** [comment]
But I like the structure. Looks fine to me

**Comment by aaronmallen** [comment]
@samsheff basically if we're going the PR route, which it looks like we are (see #15) we would scrape the PR's between tags for comments formatted like:

```
Changed
-------------
* foo
* bar
Added
-------------
* foo
* bar
```

we would be using markdown ^

**Comment by samsheff** [comment]
@aaronmallen Got it. Looks fine to me.

**Comment by aaronmallen** [comment]
:+1: I'll write out documentation for this and place it in the wiki for now. We'll want to move that documentation to either a gh-page or like a product page eventually.

**Comment by aaronmallen** [comment]
This impedes #15. Solution: Use the discussion posted here until documentation is posted in the wiki on formatting.

**Comment by aaronmallen** [comment]
@samsheff check out the wiki let me know if the documentation is sufficient. It's important to understand the formatting requirements to successfully complete #27 

https://github.com/JustShipIt/TheDepot/wiki/How-to-use-TheDepot

**Comment by samsheff** [comment]
@aaronmallen Looks good to me. Everything seems pretty simple and straightforward.
